%% Analisis de todas las mediciones de los distintos circuitos
%clc; clear; close all;

show_individuales = true;
show_parcial_tx = false;
show_parcial_rx = false;
show_full = false;
show_failed_full_fca = false;


%% Plot de los parametros S de los componentes individuales
files_individuales = {...
    "mediciones/individuales/t1_microstrip.s2p", ...
    "mediciones/individuales/t2_microstrip.s2p", ...
    "mediciones/individuales/t3_microstrip.s2p", ...
    "mediciones/individuales/fca_cha_00.s2p", ...
    "mediciones/individuales/bga616_a_5v.s2p", ...
    "mediciones/individuales/tx_amp_b_12v.s2p", ...
    "mediciones/individuales/tia_ltc_pd.s2p", ...
    "mediciones/individuales/lmh34400_pd.s2p", ...
};

if (show_individuales)
    for i=1:1:length(files_individuales)
        a = sparameters(files_individuales{i});
        figure();
        rfplot(a)
        title(files_individuales{i}, Interpreter="none")
    end
end



%% Plot de los parametros S del transmisor en conjunto
files_parciales_tx = {...
    %"mediciones/parciales_tx/t1__tx_amp.s2p", ...
    %"mediciones/parciales_tx/t2__tx_amp.s2p", ...
    %"mediciones/parciales_tx/t3__tx_amp.s2p", ...
    "mediciones/parciales_tx/t1__bga.s2p", ...
    "mediciones/parciales_tx/t2__bga.s2p", ...
    "mediciones/parciales_tx/t3__bga.s2p", ...
    "mediciones/parciales_tx/t1__bga__fca_12v.s2p", ...
    "mediciones/parciales_tx/t2__bga__fca_12v.s2p", ...
    "mediciones/parciales_tx/t3__bga__fca_12v.s2p", ...
    %"mediciones/parciales_tx/t1__tx_amp__fca.s2p", ...
    %"mediciones/parciales_tx/t2__tx_amp__fca.s2p", ...
    %"mediciones/parciales_tx/t3__tx_amp__fca.s2p", ...
};

% TODO borrar
% files_parciales_tx = {...
%     "mediciones/parciales_tx/t1__tx_amp_10v.s2p", ...           % TODO cambiar aca por 12V
%     "mediciones/parciales_tx/t1__tx_amp_10v__fca_5v.s2p", ...   % TODO cambiar aca por 12V
% };

if (show_parcial_tx)
    for i=1:1:length(files_parciales_tx)
        a = sparameters(files_parciales_tx{i});
        figure();
        rfplot(a)
        title(files_parciales_tx{i}, Interpreter="none")
    end
end


%% Plot de los parametros S del receptor en conjunto
files_parciales_rx = {...
    "mediciones/parciales_rx/fca__led__sfh203__lmh34400.s2p", ...
    "mediciones/parciales_rx/fca__led__sfh203__lmh34400__bga616.s2p", ...
    "mediciones/parciales_rx/fca__led__sfh203__lmh34400__bga616__noisy.s2p", ...
    "mediciones/parciales_rx/t1__fca__led__sfh203__lmh34400__bga616__noisy.s2p", ...
};

if (show_parcial_rx)
    for i=1:1:length(files_parciales_rx)
        a = sparameters(files_parciales_rx{i});
        figure();
        rfplot(a)
        title(files_parciales_rx{i}, Interpreter="none")
    end
end


%% Plot de los parametros S del sistema completo
files_full = {...
    "mediciones/full/t1__bga__fca12v__led21__sfh203__ltc__bga.s2p",  ...
    "mediciones/full/t2__bga__fca12v__led21__sfh203__ltc__bga.s2p",  ...
    "mediciones/full/t3__bga__fca12v__led21__sfh203__ltc__bga.s2p",  ...
};

if (show_full)
    for i=1:1:length(files_full)
        a = sparameters(files_full{i});
        figure();
        rfplot(a)
        title(files_full{i}, Interpreter="none")
    end
end

%% Plot de los parametros S con led y fotodiodo
% Este set de mediciones fallo porque el FCA estaba alimentado con 5V en
% vez de 12V, lo que se cree que hace que sature el dispositivo.
files_failed_full_fca = {...
    "mediciones/fallidas/full_fca/full_0t_pdb_tia_ltc.s2p", ...
    "mediciones/fallidas/full_fca/full_1t_pdb_tia_ltc.s2p", ...
    "mediciones/fallidas/full_fca/full_2t_pdb_tia_ltc.s2p", ...
    "mediciones/fallidas/full_fca/full_0t_sfh_tia_ltc.s2p", ...
    "mediciones/fallidas/full_fca/full_1t_sfh_tia_ltc.s2p", ...
    "mediciones/fallidas/full_fca/full_2t_sfh_tia_ltc.s2p", ...
};


if (show_failed_full_fca)
    for i=1:1:length(files_failed_full_fca)
        a = sparameters(files_failed_full_fca{i});
        figure();
        rfplot(a)
        title(files_failed_full_fca{i}, Interpreter="none")
    end
end





